### ISSUE TITLE
Question: put color picker inside a modal not work right.

### ISSUE THREAD

**Issue by Khaplann** [jsuites/jsuites#105]
i am using this css to put the colorpicker inside the modal
```css
.jcolor-content {
    bottom: 0 !important;
    top: auto !important;
}

.jcolor{
	margin-top: -136px;
	left:25px;
}

.color-picker .jcolor-input{
	width: 212px;
}

.jcolor-content {
    bottom: 0 !important;
    top: auto !important;
}

.jcolor{
	margin-top: -136px;
	left:25px;
}
```
![image](https://user-images.githubusercontent.com/71605332/140520109-41dc47e4-8bce-4ada-ba89-7325da0fb97e.png)
![image](https://user-images.githubusercontent.com/71605332/140520133-974224b2-7b2f-4af1-a31f-2cb6394d8e07.png)

when i scroll the picker dont move, but it work fine if i put in the documet like the example
https://jsuites.net/v4/color-picker
